name: vietnamese_learning
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  sign_button: ^0.0.9
  flutter_svg: ^0.19.0

  cupertino_icons: ^1.0.0
  percent_indicator: ^2.1.7+4
  flutter_signin_button: ^1.1.0
  persistent_bottom_nav_bar: any
  carousel_slider: ^2.3.1
  font_awesome_flutter: ^8.8.1
  device_simulator: ^0.9.6
  speech_to_text: ^2.7.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  flip_card: ^0.4.4
  cool_alert: ^1.0.1
  shared_preferences: ^0.5.12+2
  sweetalert: ^0.0.1
  dio: any
  bloc: any
  flutter_bloc: any
  reorderables: any
  toast: ^0.1.5
  assets_audio_player: ^2.0.12
  modal_bottom_sheet: ^0.2.2
  firebase_messaging: ^7.0.3
  file_picker: ^2.0.12
  firebase_core: ^0.5.2
  firebase_storage: ^5.0.1
  progress_dialog: ^1.2.4
  video_player: ^1.0.1
  chewie: ^0.12.0
  fijkplayer: ^0.8.7
  loadmore: ^1.0.4
  google_speech: ^1.2.1
  flutter_audio_recorder: ^0.5.5
  path_provider: ^1.6.24
  rflutter_alert: ^1.0.3
  material_design_icons_flutter: ^3.2.4495
  flutter_spinkit: ^4.1.2
  date_format: ^1.0.8
  sqflite: ^1.3.0
  chewie_audio: ^1.0.0+1
  auto_size_text: ^2.1.0
  the_validator: ^1.0.3
  form_validator: ^0.1.5
  flutter_chat_bubble: ^1.0.2
  jwt_decoder: ^1.0.3
  image_picker: ^0.6.7+14
  firebase_auth: ^0.18.3+1
  google_sign_in: ^4.5.6
  countdown: ^0.1.0
  countdown_flutter: ^0.1.2
  firebase_ml_vision: ^0.9.8
  translator: ^0.1.5
  uuid: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  flutter_gifimage: ^1.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/facebook_logo.png
     - assets/images/google_logo.png
     - assets/images/apple_logo.png
     - assets/images/twitter_logo.png
     - assets/images/vietnameselearn.png
     - assets/images/background.png
     - assets/images/tiengviet1.svg
     - assets/images/xinchaovietnam.png
     - assets/images/profile.png
     - assets/images/logo.png
     - assets/images/vietnameselearnlogo.png
     - assets/images/logolearning.png
     - assets/images/vocabulary_logo.png
     - assets/images/conversation_logo.png
     - assets/images/quiz_logo.png
     - assets/images/email.png
     - assets/images/VL.png
     - assets/images/rocket.png
     - assets/images/VLwithout.png
     - assets/images/chaohoi.png
     - assets/images/owlcolor.png
     - assets/images/owlexpertcolor.png
     - assets/images/owlwithclassescolor.png
     - assets/images/backgroundlevel.png
     - assets/images/backgroundlevel1.png
     - assets/images/demovocab/dog.png
     - assets/images/demovocab/mouse.png
     - assets/images/demovocab/bird.png
     - assets/images/demovocab/phone.png
     - assets/images/demovocab/tree.png
     - assets/images/demovocab/chicken.png
     - assets/images/demovocab/car.png
     - assets/images/demovocab/bike.png
     - assets/images/signupbackground.png
     - assets/images/app_icon.png
     - assets/images/background_icon.png
     - assets/images/matchinggame.png
     - assets/images/matchingcard.png
     - assets/images/splashscreen1.png
     - assets/images/splashscreen2.png
     - assets/images/splashscreen3.png
     - assets/images/splashscreen4.png
     - assets/images/quest.png
     - assets/images/qualification.png
     - assets/images/tryagain.png
     - assets/images/cardgame.gif
     - assets/vietnamese-master-2e898b96ecf0.json
     - assets/images/matching_game_card.png
     - assets/images/vietnamflag.png
     - assets/images/usaflag.png
     - assets/images/franceflag.png
     - assets/images/happy.png
     - assets/images/sad.png
     - assets/images/0.png
     - assets/images/1.png
     - assets/images/2.png
     - assets/images/3.png
     - assets/images/4.png
     - assets/images/5.png
     - assets/images/6.png
     - assets/images/gallow.png
     - assets/images/hangman.png
     - assets/images/correct.png
     - res/hangman_words.txt
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helveticaneue.ttf
        - asset: assets/fonts/helveticaneuebold.ttf
          weight: 900
        - asset: assets/fonts/helveticaneuebolditalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/helveticaneueitalic.ttf
          style: italic
        - asset: assets/fonts/helveticaneuelight.ttf
          weight: 500
        - asset: assets/fonts/helveticaneuelightitalic.ttf
          style: italic
          weight: 500
    - family: PatrickHand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: assets/fonts/FiraMono-Bold.ttf
        - asset: assets/fonts/FiraMono-Regular.ttf

