name: vietnamese_learning
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  sign_button: ^0.0.9
  flutter_svg: ^0.19.0

  cupertino_icons: ^0.1.3
  percent_indicator: ^2.1.7+4
  flutter_signin_button: ^1.1.0
  persistent_bottom_nav_bar: any
  font_awesome_flutter: ^8.8.1
  device_simulator: ^0.9.6
  speech_to_text: ^2.7.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  flip_card: ^0.4.4
  draggable_widget: ^1.0.1
  cool_alert: ^1.0.1
  shared_preferences: ^0.5.12+2
  sweetalert: ^0.0.1
  http: ^0.12.2
  flutter_colored_progress_indicators: ^1.2.0
  retrofit: any
  json_annotation: any
  dio: any
  bloc: any
  flutter_bloc: any
  reorderables: any
  toast: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/facebook_logo.png
     - assets/images/google_logo.png
     - assets/images/apple_logo.png
     - assets/images/twitter_logo.png
     - assets/images/vietnameselearn.png
     - assets/images/background.png
     - assets/images/tiengviet1.svg
     - assets/images/xinchaovietnam.png
     - assets/images/profile.png
     - assets/images/logo.png
     - assets/images/vietnameselearnlogo.png
     - assets/images/logolearning.png
     - assets/images/vocabulary_logo.png
     - assets/images/conversation_logo.png
     - assets/images/quiz_logo.png
     - assets/images/email.png
     - assets/images/VL.png
     - assets/images/rocket.png
     - assets/images/VLwithout.png
     - assets/images/chaohoi.png
     - assets/images/owlcolor.png
     - assets/images/owlexpertcolor.png
     - assets/images/owlwithclassescolor.png
     - assets/images/backgroundlevel.png
     - assets/images/backgroundlevel1.png
     - assets/src.json
     - assets/images/demovocab/dog.png
     - assets/images/demovocab/mouse.png
     - assets/images/demovocab/bird.png
     - assets/images/demovocab/phone.png
     - assets/images/demovocab/tree.png
     - assets/images/demovocab/chicken.png
     - assets/images/demovocab/car.png
     - assets/images/demovocab/bike.png
     - assets/images/signupbackground.png
     - assets/images/matchinggame.png
     - assets/images/matchingcard.png
     - assets/images/splashscreen1.png
     - assets/images/splashscreen2.png
     - assets/images/splashscreen3.png
     - assets/images/splashscreen4.png
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helveticaneue.ttf
        - asset: assets/fonts/helveticaneuebold.ttf
          weight: 900
        - asset: assets/fonts/helveticaneuebolditalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/helveticaneueitalic.ttf
          style: italic
        - asset: assets/fonts/helveticaneuelight.ttf
          weight: 500
        - asset: assets/fonts/helveticaneuelightitalic.ttf
          style: italic
          weight: 500

